name : "Sample React Ci Pipleline FOr test / Workflow"

on : 
    push : 
        branches :
            - main 

jobs : 
    build-and-test :
        runs-on : ubuntu-latest
        steps :
            - name: Checkout repository
              uses: actions/checkout@v4

            - name : "Setup Node js"
              uses :  actions/setup-node@v6
              with :
                  node-version : "21"

            - name : "Install Dependencies"
              run : npm install

            - name : "Done Setup"
              run : echo "Done Setup"

            - name : "Run Build"
              run : npm run build

            - name : "Downlaod Build"
              uses : actions/upload-artifact@v4
              with :
                  name : build
                  path : dist

            - name : "Done Build"
              run : echo "Done Build"

            
